# NB: don't set `language: haskell` here

sudo: false

env:
  - CABALVER=1.18 GHCVER=7.8.4
  - CABALVER=1.22 GHCVER=7.10.1
  - CABALVER=1.22 GHCVER=head

cache:
  apt: true

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-$CABALVER
      - ghc-$GHCVER

matrix:
  allow_failures:
    - env: CABALVER=1.22 GHCVER=head

before_install:
  # ghc
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  # versions
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - cabal --version

install:
  - cabal update
  - cabal install -j2 --only-dependencies --enable-tests

script:
  - cabal configure --enable-tests
  - cabal test -j2
