name: travis-meta-yaml
version: 0.1.0.0
synopsis: .travis.yml preprocessor
description: .travis.yml preprocessor
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/travis-meta-yaml
category: Development
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
  - README.md
  - fixtures/*.yml
  - data/*
  - .travis.yml
  - .travis.meta.yml

ghc-options: -Wall

dependencies:
  - base >=4.7 && <4.9
  - aeson
  - bytestring
  - file-embed >= 0.0.9
  - lens
  - lens-aeson
  - regex-applicative
  - regex-applicative-text
  - text
  - unordered-containers
  - yaml >= 0.8.13

library:
  source-dirs:
    - src

executables:
  travis-meta-yaml:
    main: Main.hs
    source-dirs: cli
    dependencies:
      - travis-meta-yaml
      - optparse-applicative

tests:
  tests:
    main: Tests.hs
    source-dirs:
      - tests
    dependencies:
      - extra
      - travis-meta-yaml
      - tasty
      - tasty-quickcheck
